### ISSUE TITLE
Updating to 1.20.2 ?

### ISSUE THREAD

**Issue by mizuo-san** [EncryptSL/CountryBlocker#1]
Is updating plugin to a newer mc version in you plans?

**Comment by EncryptSL** [comment]
There is updated version, with 1.20.x support, by default plugin supporting plugins 1.18 > 1.20.x 
https://github.com/EncryptSL/CountryBlocker/releases/tag/v1.0.3-SNAPSHOT

Plugin need only update GeoLite database with countries, manually.
If you have another questions you can create new issue.

**Comment by mizuo-san** [comment]
Thank You!
